name: Ping Render API Manually & Scheduled

on:
  # For manual trigger from GitHub UI
  workflow_dispatch:

  # Scheduled at 8 PM, 3 PM and 4 PM IST (14:30 and 16:30 UTC)
  schedule:
    - cron: "30 14 * * *"
    - cron: "30 9 * * *"
    - cron: "30 10 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render server
        run: |
          curl -X GET "https://codeping-be.onrender.com/ping" \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -H "Accept: application/json" \
            -H "Connection: keep-alive" \
            -H "Referer: https://codeping-v1.vercel.app/"
